version: 2.1
jobs:
  step-1:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: "This is the first step"
          command: |
            echo 'simply'
            echo 'created!'
      - run:
          name: "build docker image"
          command: |
            docker build -t snsinahub/circleci-migration:1.0.0 .
workflows:
  start-step-1:
    jobs:
      - step-1


    