version: 2.1
jobs:
  step-1:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "install dependencies"
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: "RUN npm"
          command: |
            npm install
      - run:
          name: "build docker image"
          command: |
            docker build -t snsinahub/circleci-migration:1.0.0 .
workflows:
  start-step-1:
    jobs:
      - step-1


    