version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
        name: "This is the first step"
        command: |
          echo 'simply'
          echo 'created!'
    