version: 2.1
orbs: 
  docker: circleci/docker@2.0.2
jobs:
  step-1:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "install dependencies"
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install --upgrade pip \
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76 
      - run:
          name: "build docker image"
          command: |
            docker build -t snsinahub-valet/circleci-migration:1.0.0 .            
  step-2:
    executor: 
      name: docker/docker
      tag: '3.6'
    environment: ""
      DOCKER_LOGIN
    steps:
      - checkout
      - docker/install-docker-tools
      - docker/check
      - docker/build:
          image: snsinahub-valet/aws-migration:latest      
workflows:
  start-step-1:
    jobs:
      - step-1
  start-step-2:
    jobs:
      - step-2


    
